### ISSUE TITLE
Problem with modification of the BLE application 

### ISSUE THREAD

**Issue by viralpatel9** [NordicSemiconductor/pc-nrfconnect-ble#277]
I downloaded the BLE framework to build an app from it, but seems like it is missing the files, and index.tsx shows only Install path instead of whole app. everything seems to be missing. There are no libraries

**Comment by datenreisender** [comment]
Yes, this was changed to be mainly only a proxy app which installs the actual app, because we mostly froze the app. If you are looking for the source of the “real” app, you can find it at https://github.com/NordicPlayground/pc-nrfconnect-ble-standalone/tree/main/pc-nrfconnect-ble.

But please not that it is also pretty outdated and does not support more recent Bluetooth features.
