### ISSUE TITLE
default dependencies not working

### ISSUE THREAD

**Issue by Kunzro** [NordicSemiconductor/pc-nrfconnect-ble#278]
Hey Everyone,

I cloned your repo and tried to build it as explained in the [Docs](https://nordicsemiconductor.github.io/pc-nrfconnect-docs/app_development), however I got the following errors: 

```
Error: Build failed with 5 errors:
node_modules/pc-nrfconnect-shared/src/Alert/Alert.module.scss:1:7: ERROR: Do not know how to load path: esbuild-sass-plugin:css-chunk:node_modulespc-nrfconnect-sharedsrcAlertAlert.module.scss
node_modules/pc-nrfconnect-shared/src/Button/button.module.scss:1:7: ERROR: Do not know how to load path: esbuild-sass-plugin:css-chunk:node_modulespc-nrfconnect-sharedsrcButtoutton.module.scss
node_modules/pc-nrfconnect-shared/src/Card/card.module.scss:1:7: ERROR: Do not know how to load path: esbuild-sass-plugin:css-chunk:node_modulespc-nrfconnect-sharedsrcCardcard.module.scss
node_modules/pc-nrfconnect-shared/src/Dropdown/Dropdown.module.scss:1:7: ERROR: Do not know how to load path: esbuild-sass-plugin:css-chunk:node_modulespc-nrfconnect-sharedsrcDropdownDropdown.module.scss
node_modules/pc-nrfconnect-shared/src/MasonryLayout/masonryLayout.module.scss:1:7: ERROR: Do not know how to load path: esbuild-sass-plugin:css-chunk:node_modulespc-nrfconnect-sharedsrcMasonryLayoutmasonryLayout.module.scss
```

However installing [esbuild-sass-plugin](https://www.npmjs.com/package/esbuild-sass-plugin) manually with the following command fixed it.

`npm install esbuild-sass-plugin --save`

also running

`npm ci`

returns a lot of warnings:

**26 vulnerabilities (3 moderate, 22 high, 1 critical)**

**To address issues that do not require attention, run:**
  **npm audit fix**

**Some issues need review, and may require choosing**
**a different dependency.**

Setup:
Node.js version 18.16.0
npm version 9.5.1
on Windows 10

Commands to init run:
git clone https://github.com/NordicSemiconductor/pc-nrfconnect-ble.git
cd pc-nrfconnect-ble
npm ci
npm build:dev  ----> fails
npm install esbuild-sass-plugin --save
npm build:dev ----> works

I am very new to Node.js and very much apreciate your help. Are the warnings of any concern and does manually installing esbuild-sass-plugin indicate an incorrect setup, or are the dependencies just outdated?

Best

**Comment by datenreisender** [comment]
Hi @Kunzro,

sorry for the slow response and that our documentation is not very well tailored towards new developers. The _very_ vast majority of development on nRF Connect for Desktop and its apps is done in-house at Nordic Semiconductor and because of that we, unfortunately, sometimes have less of an eye on other developers.

I just tested it and for me compiling this project works out of the box, without the need of manually installing esbuild-sass-plugin, both on my machine or [on a build-server](https://dev.azure.com/NordicSemiconductor/Wayland/_build/results?buildId=51574&view=results). Still, of course it could be, that there is something wrong with this project.

But, I am more curious why you even want to build this project. Especially _this_ project, because it only is a small wrapper app, which effectively downloads the real BLE app (found at https://github.com/NordicPlayground/pc-nrfconnect-ble-standalone/tree/main/pc-nrfconnect-ble) which itself isn't currently actively updated anymore, but may eventually be replaced by a new BLE app.

**Comment by Kunzro** [comment]
Hey @datenreisender 

Thank you very much for your response!
You are right, I am actually indeed more interested in the "real standalone" BLE app (It took me a while to understand that this is just a small wrapper).

Again thanks for the help and have a nice day!
