### ISSUE TITLE
Segger JLink does not match expected is 7.96 expected 7.88j

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/pc-nrfconnect-ble#289]
Installed Segger Universal 796 now

nRFconnect complains:

```
2024-03-11T00:11:28.994Z INFO Using JLink version: 
JLink_V7.96 

2024-03-11T00:11:28.994Z WARN Installed JLink version 
does not match the expected version (JLink_V7.88j)
```

now :
```19:45:11.705	Using JLink version: JLink_V7.96
19:45:11.806	Installed JLink version does not match the provided version (V7.66a)
19:45:11.809	Updated list of uuids with data from https://github.com/NordicSemiconductor/bluetooth-numbers-database/tree/master/v1
```

**Comment by datenreisender** [comment]
It is only a warning, because the mentioned JLink versions are the one we tested that release with, but usually it also works with a more recent version of JLink.

In your two snippets above the one mentioning `V7.66a` is probably the Bluetooth LE app while the other snippet mentioning `V7.88j` is from another, recent app. This is, because the Bluetooth LE app is sadly stuck in the past at the moment, until we are able to provide an updated version of it. 

But mostly a more recent version of JLink should be ok anyhow. I hope this clears it up for you.
